name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout do código
      - uses: actions/checkout@v3

      # Configurar Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm' # Cache de dependências

      # Instalar dependências e buildar
      - name: Build web-app
        env:
          NODE_ENV: production
        run: |
          npm install
          npm run build
          
       - name: Install dependencies
        run: npm ci

      - name: Verify Vite installation
        run: npm list vite || npm install vite --save-dev

      - name: Build web-app
        run: npm run build

      # Deploy para o GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Substitua por ./build se for o diretório correto
